version: '3.8'

services:
  neo4j-admin:
    image: 'neo4j/neo4j-admin:5.7.0-community'
    env_file: .env
    tty: true
    # command: /bin/bash -c 'neo4j-admin load --verbose --force --database=neo4j --from=/var/lib/neo4j/dump/alzkb.dump'
    command: /bin/bash -c 'neo4j-admin database load --verbose --overwrite-destination=true --from-path=/var/lib/neo4j/dump neo4j'
    volumes:
      - '${ALZKB_DATA_ROOT}/neo4j/data:/var/lib/neo4j/data'
      - '${ALZKB_DATA_ROOT}/neo4j/logs:/var/lib/neo4j/logs'
      - './neo4j/dump:/var/lib/neo4j/dump'
